// PM2 Ecosystem Configuration
// Auto-generated by Wingman - do not edit manually
module.exports = {
  "apps": [
    {
      "name": "honest-ivory-thicket-app-word5",
      "namespace": "wingman-apps",
      "script": "bash",
      "args": [
        "-c",
        "set -a; [ -f .env ] && . ./.env; set +a; export APP_ID='416e201b-682b-4795-b7dc-6ce7bfbf003a' APP_LABEL='Word5' USER_ALIAS='honest-ivory-thicket' PORT=41005; npm start"
      ],
      "cwd": "/Users/mini/code/games/word5",
      "out_file": "/Users/mini/code/games/word5/apps/logs/honest-ivory-thicket-app-word5-out.log",
      "error_file": "/Users/mini/code/games/word5/apps/logs/honest-ivory-thicket-app-word5-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    }
  ]
};
